version: "3.8"

services:
  # Service untuk item-app
  item-app:
    image: ekaramadhan35/item-app:v1 # Menggunakan image item-app yang sudah di-build dan di-push ke Docker Hub (atau GitHub Packages)
    ports:
      - "80:8080" # Port mapping: Host port 80 -> Container port 8080
    depends_on:
      - item-db # Pastikan item-app hanya berjalan setelah item-db diluncurkan
    restart: always # Restart container jika terhenti atau gagal

  # Service untuk item-db (MongoDB)
  item-db:
    image: mongo:3 # Menggunakan image mongo versi 3 dari Docker Hub
    restart: always # Restart container jika terhenti atau gagal
    volumes:
      - app-db:/data/db # Menggunakan volume app-db untuk menyimpan data MongoDB secara persisten

# Definisi volume untuk menyimpan data MongoDB secara persisten
volumes:
  app-db:
